sudo: required
language: node_js
node_js:
  - '0.10'
before_install:
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq wine
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - gulp all
  - gulp build --build all
cache:
  directories:
    - node_modules
    - cache
before_deploy: 
  - sh zip-release.sh
  - git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: AB6SPSgp/+opintYfgTkv0mzdMLElgFptYYR8bVosK5V7qyEts2l9NBeEuXDKKfT758QBkA151pD4nXegihfTp0whpyce4F099SxPlc0tzcfbfXVlWR/A5F3HAUjdFcNQCR6kWlcR1Opkmhp7Ep//F7sY4keJzD0rSLn8O4jKDE=
  file_glob: true
  skip_cleanup: true
  file: 
    - build/Chatter/*.zip
  on:
    repo: Jake0oo0/chatter
    tags: true
    all_branches: true